name: CD (Build and deploy to production)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install Clasp
        run: |
          npm init -y
          npm install @google/clasp -g
      - name: Create clasprc.json & crasp.json
        run: |
          echo \{\"scriptId\":\"${{ secrets.SCRIPT_ID}}\",\"rootDir\":\"./src\"\} > ~/.clasp.json
          echo \{\"token\":\{\"access_token\":\"${{ secrets.ACCESS_TOKEN}}\",\"scope\":\"https://www.googleapis.com/auth/presentations https://www.googleapis.com/auth/script.webapp.deploy https://www.googleapis.com/auth/script.external_request https://www.googleapis.com/auth/drive https://mail.google.com/ https://www.googleapis.com/auth/spreadsheets\",\"token_type\":\"Bearer\",\"expiry_date\":1620870307822,\"refresh_token\":\"${{ secrets.REFRESH_TOKEN }}\"\},\"oauth2ClientSettings\":\{\"clientId\":\"${{ secrets.CLIENT_ID }}\",\"clientSecret\":\"${{ secrets.CLIENT_SECRET }}\",\"redirectUri\":\"http://localhost\"\},\"isLocalCreds\":true\} > ~/.clasprc.json
      - name: Deploy
        run: |
          clasp push
          clasp deploy -d ${GITHUB_REF##*/}
