name: CI (Test Clasp Push)

on:
  push:
    branches:
      - "*"
  workflow_dispatch:
env:
  #URL for posting job results to slack
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: npm install jest
      - name: Run test
        run: npx jest
      - name: Coverage test
        run: npx jest --coverage
      # 失敗時はこちらのステップが実行される
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_CHANNEL: alert_ci
          SLACK_TITLE: Test Failure
          SLACK_COLOR: danger
  commit:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      diffCount: ${{ steps.changes.outputs.count }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm i -D typescript @types/node @types/google-apps-script
          npm i -D webpack webpack-cli ts-loader gas-webpack-plugin
          npm run build
      - name: Count changes
        id: changes
        run: echo "::set-output name=count::$(git diff --name-only | wc -l)"
      - name: Update openapi.json
        if: steps.changes.outputs.count > 0
        run: |
          git add --update
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Automatin npm build updte"
          git push
  clasp_push:
    needs: commit
    runs-on: ubuntu-latest
    if: ${{ needs.commit.outputs.diffCount }} > 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install Clasp
        run: |
          npm install @google/clasp -g
          npm i -D typescript @types/node @types/google-apps-script
          npm i -D webpack webpack-cli ts-loader gas-webpack-plugin
      - name: Create clasprc.json & crasp.json
        run: |
          echo \{\"scriptId\":\"${{ secrets.SCRIPT_ID}}\",\"rootDir\":\"./dist\"\,\"projectId\": \"${{ secrets.PROJECT_ID}}\"} > ~/.clasp.json
          echo \{\"token\":\{\"access_token\":\"${{ secrets.ACCESS_TOKEN}}\",\"scope\":\"https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/script.webapp.deploy https://www.googleapis.com/auth/logging.read openid https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/cloud-platform\",\"token_type\":\"Bearer\",\"id_token\":\"${{ secrets.ID_TOKEN }}\",\"expiry_date\":1620870307822,\"refresh_token\":\"${{ secrets.REFRESH_TOKEN }}\"\},\"oauth2ClientSettings\":\{\"clientId\":\"${{ secrets.CLIENT_ID }}\",\"clientSecret\":\"${{ secrets.CLIENT_SECRET }}\",\"redirectUri\":\"http://localhost\"\},\"isLocalCreds\":false\} > ~/.clasprc.json
      - name: Push
        run: |
          clasp push
      # 成功時はこちらのステップが実行される
      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: alert_ci
          SLACK_TITLE: Deploy Success
          SLACK_COLOR: good
      # 失敗時はこちらのステップが実行される
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_CHANNEL: alert_ci
          SLACK_TITLE: Deploy Failure
          SLACK_COLOR: danger
